Определение типа перекрёстка
moevm/mse_indefinite_nav_ml pull request #28
Opened 2022-04-08 11:06 UTC by Crunchy0

Написана обёртка TileWrapper, позволяющая получать доступ к клеткам поля и определять тип клетки, которая находится перед агентом. На данный момент распознаются перекрёстки двух типов: 3way_left и 4way. При необходимости возможно изменение множества распознаваемых клеток.

2022-04-08 12:02 UTC, Crunchy0 commented
На скриншоте ниже агент проехал X-перекрёсток и направлялся в сторону T- перекрёстка.

![screenshot](https://user-images.githubusercontent.com/55055449/162431248-ce7b470f-7507-4263-8725-56a6092cda76.png)

2022-04-08 14:04 UTC, YuriyKortev requested changes

2022-04-08 14:04 UTC, YuriyKortev commented on gym_custom/wrappers/envWrapper.py
> +    def next_tile(self, tc, pos, phi):
добавить статическое типизирование

2022-04-08 14:04 UTC, YuriyKortev commented on gym_custom/wrappers/envWrapper.py
> +        if sin(phi) == 0 or cos(phi) == 0: # Если взгляд перпендикулярен тайлу
if dx == 0 or dy == 0:

2022-04-08 14:04 UTC, YuriyKortev commented on gym_custom/wrappers/envWrapper.py
> +            cons_next.append( [tc[0] + dx, tc[1] + dy] )
cons_next.append( [tcx, tcy] )

2022-04-08 14:04 UTC, YuriyKortev commented on gym_custom/wrappers/envWrapper.py
> +
заменить int(cos(phi) < 0) на dx,

 tc[1] + int(phi < 0) вы тут cos не забыли?

2022-04-08 14:04 UTC, YuriyKortev commented on gym_custom/wrappers/envWrapper.py
> +        return None
переопределите метод step, вызывайте внутри next_tile и сохраняйте результат в info, не забудьте вызвать родительский step

2022-04-08 14:04 UTC, YuriyKortev commented on tools/run.py
>              obs, reward, done, info = env.step(action)
берите тип клетки из info

2022-04-09 17:26 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +    def next_tile(self, tc, pos, phi):
Выполнено.

2022-04-09 17:26 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +        if sin(phi) == 0 or cos(phi) == 0: # Если взгляд перпендикулярен тайлу
Выполнено

2022-04-09 17:27 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +            cons_next.append( [tc[0] + dx, tc[1] + dy] )
Выполнено

2022-04-09 17:29 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +
Косинус не забыл, там нужен синус был, что равносильно знаку угла от -pi до pi.
Заменил также остальные части.

2022-04-09 17:29 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +        return None
Выполнено

2022-04-09 17:29 UTC, Crunchy0 commented on tools/run.py
>              obs, reward, done, info = env.step(action)
Выполнено

2022-04-09 19:43 UTC, YuriyKortev requested changes

2022-04-09 19:43 UTC, YuriyKortev commented on tools/run.py
> +            if info["Simulator"]["next_crossroad"]:
потенциальный эксепшн

if "next_crossroad" in info["Simulator"] and info["Simulator"]["next_crossroad"]:

2022-04-10 08:11 UTC, Crunchy0 commented on tools/run.py
> +            if info["Simulator"]["next_crossroad"]:
Выполнено

2022-04-10 11:27 UTC, YuriyKortev commented on tools/run.py
> +            if "next_crossroad" in info["Simulator"].keys() and info["Simulator"]["next_crossroad"]:
сложность "next_crossroad" in info["Simulator"].keys() - O(N)
сложность "next_crossroad" in info["Simulator"] - O(1)
так что предпочтительнее все таки 2й вариант

2022-04-10 12:44 UTC, YuriyKortev commented on tools/run.py
> +            if "next_crossroad" in info["Simulator"].keys() and info["Simulator"]["next_crossroad"]:
кстати я не прав оказался, keys() возвращает не list а dict_keys, который также использует хэш

2022-04-10 13:08 UTC, Crunchy0 commented on tools/run.py
> +            if "next_crossroad" in info["Simulator"].keys() and info["Simulator"]["next_crossroad"]:
В таком случае, полагаю, больше ничего исправлять не надо.

2022-04-10 13:20 UTC, YuriyKortev commented on tools/run.py
> +            if "next_crossroad" in info["Simulator"].keys() and info["Simulator"]["next_crossroad"]:
не надо, таска в done

2022-04-11 16:03 UTC, AndrewGavril approved these changes

2022-04-11 16:04 UTC, merged