Состояние при нахождении на перекрёстке
moevm/mse_indefinite_nav_ml pull request #35
Opened 2022-04-15 17:31 UTC by Crunchy0

В метод step класса TileWrapper добавлен случайный выбор одного из допустимых направлений поворота (или просто движения, если бот не находится на перекрёстке). Поле класса state содержит целое значение, обозначающее выбранное направление движения в текущей клетке.
Переименован метод next_tile, так как не вполне корректно отражал суть выполняемых методом действий.

2022-04-16 12:18 UTC, AndrewGavril requested changes

2022-04-16 12:18 UTC, AndrewGavril commented on gym_custom/wrappers/envWrapper.py
> +       self._cr_dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
Лучше использовать словарь, чтобы было ясно, что означает каждый элемент списка

2022-04-16 12:18 UTC, AndrewGavril commented on gym_custom/wrappers/envWrapper.py
> +       self._cr_dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
Или заменить элементы на константы именованные

2022-04-16 12:18 UTC, AndrewGavril commented on gym_custom/wrappers/envWrapper.py
> +           "curve_left": ["laneFollowing"],
Зачем этот элемент? Почему тогда нет curve_right?

2022-04-16 13:23 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +       self._cr_dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
Мне кажется, здесь лучше как раз перечисление. Могу сделать его?

2022-04-16 13:29 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +           "curve_left": ["laneFollowing"],
Потому что карты, насколько я понял, не включают этот вид тайлов. curve_right - это, по сути, повёрнутая на pi/2 curve_left. Этот элемент в словаре нужен, потому что мы получаем список движений по ключу, который является строкой, и списки движений у разных тайлов могут совпадать.

2022-04-16 16:20 UTC, AndrewGavril commented
Согласовать код с предыдущим PR #34

2022-04-16 19:15 UTC, Crunchy0 commented
Введён словарь, ключами которого являются строки, обозначающие ориентацию перекрёстка (North, West, South, East), а значениями - векторы, каждый из которых соответствует определённой ориентации.

2022-04-16 19:15 UTC, Crunchy0 commented on gym_custom/wrappers/envWrapper.py
> +       self._cr_dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
Выполнено

2022-04-18 08:59 UTC, AndrewGavril approved these changes

2022-04-18 08:59 UTC, merged